import { randomUUID } from 'crypto';
import { contentNodeSchema, manualSchema } from '@docunest/schema';
import { logger } from '@docunest/utils';
import { Queue, Worker } from 'bullmq';
import IORedis from 'ioredis';
import { prisma } from './db.js';
import { env } from './config/env.js';
import { upsertVectors } from './vector/qdrant.js';

type IngestJob = {
  tenantId: string;
  productId: string;
  locale: string;
  url?: string;
  fileKey?: string;
};

type EmbedJob = {
  manualRecordId: string;
};

const VECTOR_COLLECTION = 'manual-chunks';

const connection = new IORedis(env.REDIS_URL);
const ingestQueue = new Queue<IngestJob>('ingest', { connection });
const embedQueue = new Queue<EmbedJob>('embed', { connection });

const buildZeroVector = () => Array.from({ length: 768 }, () => 0);

const chunkText = (text: string, size = 400): string[] => {
  const chunks: string[] = [];
  let pointer = 0;
  while (pointer < text.length) {
    const next = text.slice(pointer, pointer + size);
    chunks.push(next);
    pointer += size;
  }
  return chunks;
};

export const startWorker = () => {
  const ingestWorker = new Worker<IngestJob>(
    'ingest',
    async (job) => {
      const { tenantId, productId, locale, url, fileKey } = job.data;
      const product = await prisma.product.findUnique({ where: { id: productId } });
      if (!product) {
        throw new Error(`Product ${productId} not found`);
      }

      const manualData = manualSchema.parse({
        manualId: randomUUID(),
        tenantId,
        product: {
          productId: product.id,
          model: product.model,
          sku: product.sku,
        },
        version: new Date().toISOString(),
        locale,
        sections: [
          {
            id: randomUUID(),
            title: 'Imported Content',
            order: 1,
            content: [
              {
                type: 'paragraph',
                text:
                  'This manual was generated by the ingest worker. Replace with parsed document content.',
              },
              ...(url
                ? [
                    {
                      type: 'paragraph' as const,
                      text: `Source URL: ${url}`,
                    },
                  ]
                : []),
              ...(fileKey
                ? [
                    {
                      type: 'paragraph' as const,
                      text: `Source File Key: ${fileKey}`,
                    },
                  ]
                : []),
            ],
          },
        ],
      });

      const manual = await prisma.manual.create({
        data: {
          tenantId: manualData.tenantId,
          productId: manualData.product.productId,
          manualId: manualData.manualId,
          version: manualData.version,
          locale: manualData.locale,
          sections: {
            create: manualData.sections.map((section) => ({
              id: section.id,
              title: section.title,
              order: section.order,
              content: section.content,
            })),
          },
        },
      });

      await embedQueue.add('embed-manual', { manualRecordId: manual.id });

      return { manualId: manual.id };
    },
    { connection },
  );

  const embedWorker = new Worker<EmbedJob>(
    'embed',
    async (job) => {
      const manual = await prisma.manual.findUnique({
        where: { id: job.data.manualRecordId },
        include: { sections: true },
      });
      if (!manual) {
        throw new Error(`Manual ${job.data.manualRecordId} not found`);
      }

      await prisma.embeddingChunk.deleteMany({ where: { manualId: manual.id } });

      const points: { id: string; vector: number[]; payload: Record<string, unknown> }[] = [];

      for (const section of manual.sections) {
        const contentNodes = contentNodeSchema.array().parse((section.content as unknown[]) ?? []);
        const text = contentNodes
          .filter((node) => node.type === 'paragraph')
          .map((node) => node.text)
          .join('\n');

        if (!text) {
          continue;
        }

        const chunks = chunkText(text);
        let index = 0;
        for (const chunk of chunks) {
          const payload = {
            tenantId: manual.tenantId,
            productId: manual.productId,
            manualId: manual.manualId,
            manualRecordId: manual.id,
            sectionId: section.id,
            locale: manual.locale,
            text: chunk,
            chunkIndex: index,
          } as const;

          await prisma.embeddingChunk.create({
            data: {
              manualId: manual.id,
              sectionId: section.id,
              locale: manual.locale,
              text: chunk,
              vector: buildZeroVector(),
            },
          });

          points.push({
            id: `${manual.id}:${section.id}:${index}`,
            vector: buildZeroVector(),
            payload,
          });

          index += 1;
        }
      }

      await upsertVectors(VECTOR_COLLECTION, points);

      return { chunks: points.length };
    },
    { connection },
  );

  const logWorkerEvents = (name: string, worker: Worker) => {
    worker.on('completed', (job) => {
      logger.info({ queue: name, jobId: job.id }, 'Job completed');
    });
    worker.on('failed', (job, err) => {
      logger.error({ queue: name, jobId: job?.id, err }, 'Job failed');
    });
  };

  logWorkerEvents('ingest', ingestWorker);
  logWorkerEvents('embed', embedWorker);

  return { ingestWorker, embedWorker, ingestQueue, embedQueue };
};
